"""Generated by scripts/build_config.py --sync; do not edit manually."""

from __future__ import annotations

PACKAGE_NAME = 'workswarm'
VERSION = '0.2.5.beta1'
DISPLAY_NAME = 'WorkSwarm'
EXECUTABLE_NAME = 'workswarm'
BUNDLE_IDENTIFIER = 'com.workswarm.desktop'
ERROR_LOG_NAME = 'workswarm_exe_error.log'
TUI_PACKAGE_NAME = 'workswarm-tui'
APP_FULL_NAME = 'WorkSwarm 0.2.5.beta1'
APP_BUNDLE_NAME = 'WorkSwarm.app'
EXECUTABLE_NAME_WINDOWS = 'workswarm.exe'
DIST_DIR_NAME = 'workswarm'
DMG_FILENAME = 'WorkSwarm-0.2.5.beta1-macos.dmg'
SETUP_BASE_NAME = 'WorkSwarm-0.2.5.beta1-windows'
SETUP_FILENAME = 'WorkSwarm-0.2.5.beta1-windows.exe'
